### ISSUE TITLE
At times , wrong fields appearing in the output of predecessors.sh

### ISSUE THREAD

**Issue by PaulDaviesC** [PaulDaviesC/Logging-limits.conf#3]
It is due to the fact that the number of fields in the system call log of the audit system varies. Thus the approach of selecting fixed field assuming that it is the required field is flawed. It may require the porting of the predecessors.sh to a python script.

**Comment by pocha** [comment]
anyway, I will have a look.

**Comment by PaulDaviesC** [comment]
Note-to-self: One more reason why predecessors.sh must be redesigned. It is not compatible with the time stamps generated by the preprocess.py (notify.sh).
